apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJ1Z0F3SUJBZ0lNRmpJb1hMSXZrdmN0TFdycU1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1qQXdPVEEwTURrek9UVTJXaGNOTXpBd09UQTBNRGt6T1RVMgpXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQWxtUkRkTk5YZlI3ZzhXTXc2d1puQVRPWDBJOHhza28wNWRSK01DYzloOUt4UVkraitBaXUKSUZ3Vk1TeTgvV3BIMS9paDJHdzk2NmZuWmR3NHkrUWlIZDA0WnJ1SmsxS0tDQVAySGVvVTZNVW5iWGUzTk9RYgpTam05WEJDczBBNCtpR3R3YkRQa3gyK0lrVS96YWJxcXAvRzY3OHpqOGRDS0tlQ2NhWnhqOFlzWnJzUE5wRTBqCkhxSDlIcHdwd2xGMkNlTXprMDlzY1J1S3ZjWGZXMlNqQ0Y0TTlJaXBJZStBTHE0SnEzT3YrenVBWEl3OWs2Q2YKUFdBdGV4TDIvUlZaeVVBL2RUWHlTaXRDMmpRYkxBVmlqeWt2OXAzOVQzQ2ExdDRPRUlUb0VDVjU5bG43NW9zdwo0cmZoc2hUcjI3VWZpL0cvZlFyY0NyOXhnNHRneXhwVWF3SURBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFqcTZISlQ3ZWRnZm4KQVRRdDVaZWdua0ppZlVENUkxdTh5TUhrK0VFVWVoKzJiSkFBa3dLS2hFVW4rMTllRmdST3JkRDJzaHVzK0cwVQpROTl6OWM0RHhyTkJwMG5rcmNCeklFZUhpOXFvQmVlei9WNDI4ZWxtYURSUTYrT0did2J3REVKT3A0cy9hVVhkCkJjeXpBcGROUGt5SG1EdjhtMEJlNjVUMHhVQzY2NzZrVHVGckw5ZWt2ZDB2UzVXd0tjc1RwOXNZMi9QeVY0cGQKcVBWS29jQmdlM2NKWHNucWZXV0U0VmRNdUhxbFAvU2pqc1J3TDc5c05PVnRWOGtNV2FEQjczVUdEdlJhNXFiSgpLL1NQWVJtUG1MQzRzOW5xTU01Mk91TUdCa0VBK1dSM2JNOUk1WWFGQkVwUEpSakh4U1JaZnFQMFlkemMvM3RZCjNidHdDb3RhMWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: a3ViZS1wdWJsaWM=
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrNHpiMVkzV0dabk1YSm1ObGR2YjI5SlRqTnRZazV2TFhaalNYcHdZMlo0Y0daT2EybDFRVWRmZGtVaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYQjFZbXhwWXlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKa1pXWmhkV3gwTFhSdmEyVnVMVzF4YkRad0lpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVibUZ0WlNJNkltUmxabUYxYkhRaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNTFhV1FpT2lKak1HWXpZV1l3TWkwME5EVmlMVFJrTmprdE9EZGxPUzB6WW1NeE16YzJNalZoWlRnaUxDSnpkV0lpT2lKemVYTjBaVzA2YzJWeWRtbGpaV0ZqWTI5MWJuUTZhM1ZpWlMxd2RXSnNhV002WkdWbVlYVnNkQ0o5LmtVWTl5MG8zTGhHYzRJQWJYSGtJMDRBTmo5eTh1bDdRN1VKYXVKRmxqNmFNMl85ejFnbUMweHJXaFN3SjNsWnJiMzU5UUdfZ2ZDWFFsdUVqNVFTMnI0bER3T2RCdlFjV0Qzd3hjUkF4aEJwdXoyUnBLeTNoTEg3bHNEcjJQeGlQNFJVTjBNRmVYamE4amR1Z1FCMGV2TEZCc3BST1RFbFRKaVFEN0p2aHUzVEJVSjZ2UjFKSXBXQ1BWUTJBTzE1eFl6cG0wQUtWX1llTWExWXdXc2tFaXVmc3lNOGllb0Qzck9EWmJxVTBSQ0w5cWFZaFc2TWdCSEM4LW5yRnNCRkVoRUIzOE5tREs2ZWEyUW91M1R1blZwa3NCUTZzUkZaNUVpQm5wWDRQWE1uV09PODllNVRXLUhtc1k5TjV4UW9OanViQUsxdU81Qks1OTdZbkRvWVJFUQ==
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: c0f3af02-445b-4d69-87e9-3bc137625ae8
  creationTimestamp: "2020-09-06T09:45:52Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-06T09:45:52Z"
  name: default-token-mql6p
  namespace: kube-public
type: kubernetes.io/service-account-token
