apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"labels":{"k8s-addon":"kops-controller.addons.k8s.io"},"name":"kops-controller"},"rules":[{"apiGroups":[""],"resources":["nodes"],"verbs":["get","list","watch","patch"]}]}
  creationTimestamp: "2020-09-06T09:45:36Z"
  labels:
    k8s-addon: kops-controller.addons.k8s.io
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:k8s-addon: {}
      f:rules: {}
    manager: kubectl
    operation: Update
    time: "2020-09-06T09:45:36Z"
  name: kops-controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - patch
