apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2020-09-06T09:45:31Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:phase: {}
    manager: kube-apiserver
    operation: Update
    time: "2020-09-06T09:45:31Z"
  name: kube-node-lease
spec:
  finalizers:
  - kubernetes
