allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"},"labels":{"k8s-addon":"storage-aws.addons.k8s.io"},"name":"kops-ssd-1-17"},"parameters":{"encrypted":"true","type":"gp2"},"provisioner":"kubernetes.io/aws-ebs","volumeBindingMode":"WaitForFirstConsumer"}
    storageclass.beta.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2020-09-06T09:45:36Z"
  labels:
    k8s-addon: storage-aws.addons.k8s.io
  managedFields:
  - apiVersion: storage.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:allowVolumeExpansion: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:storageclass.beta.kubernetes.io/is-default-class: {}
        f:labels:
          .: {}
          f:k8s-addon: {}
      f:parameters:
        .: {}
        f:encrypted: {}
        f:type: {}
      f:provisioner: {}
      f:reclaimPolicy: {}
      f:volumeBindingMode: {}
    manager: kubectl
    operation: Update
    time: "2020-09-06T09:45:36Z"
  name: kops-ssd-1-17
parameters:
  encrypted: "true"
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
