apiVersion: v1
kind: LimitRange
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"LimitRange","metadata":{"annotations":{},"name":"limits","namespace":"default"},"spec":{"limits":[{"defaultRequest":{"cpu":"100m"},"type":"Container"}]}}
  creationTimestamp: "2020-09-06T09:45:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:limits: {}
    manager: kubectl
    operation: Update
    time: "2020-09-06T09:45:35Z"
  name: limits
  namespace: default
spec:
  limits:
  - defaultRequest:
      cpu: 100m
    type: Container
