apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"ip-172-20-47-215_37dc3efb-5c16-4403-af41-313b050a250c","leaseDurationSeconds":15,"acquireTime":"2020-09-06T09:45:34Z","renewTime":"2020-09-06T10:36:57Z","leaderTransitions":0}'
  creationTimestamp: "2020-09-06T09:45:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:control-plane.alpha.kubernetes.io/leader: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-06T10:36:57Z"
  name: kube-controller-manager
  namespace: kube-system
