apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2020-09-06T09:45:52Z"
involvedObject:
  apiVersion: apps/v1
  kind: Deployment
  name: kube-dns-autoscaler
  namespace: kube-system
  resourceVersion: "157"
  uid: 0721d30d-0144-44cc-9781-de1cf548b41e
kind: Event
lastTimestamp: "2020-09-06T09:45:52Z"
message: Scaled up replica set kube-dns-autoscaler-cd7778b7b to 1
metadata:
  creationTimestamp: "2020-09-06T09:45:52Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject:
        f:apiVersion: {}
        f:kind: {}
        f:name: {}
        f:namespace: {}
        f:resourceVersion: {}
        f:uid: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-06T09:45:52Z"
  name: kube-dns-autoscaler.163228afb715cb70
  namespace: kube-system
reason: ScalingReplicaSet
reportingComponent: ""
reportingInstance: ""
source:
  component: deployment-controller
type: Normal
