apiVersion: events.k8s.io/v1beta1
deprecatedCount: 1
deprecatedFirstTimestamp: "2020-09-06T09:47:52Z"
deprecatedLastTimestamp: "2020-09-06T09:47:52Z"
deprecatedSource:
  component: deployment-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2020-09-06T09:47:52Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject:
        f:apiVersion: {}
        f:kind: {}
        f:name: {}
        f:namespace: {}
        f:resourceVersion: {}
        f:uid: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-06T09:47:52Z"
  name: kube-dns.163228cb88a4f560
  namespace: kube-system
note: Scaled up replica set kube-dns-64f86fb8dd to 2
reason: ScalingReplicaSet
regarding:
  apiVersion: apps/v1
  kind: Deployment
  name: kube-dns
  namespace: kube-system
  resourceVersion: "686"
  uid: a117ef7b-4b3f-49db-9ad6-997d2df0d4c1
type: Normal
