apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2020-09-06T09:46:37Z"
involvedObject:
  apiVersion: apps/v1
  kind: DaemonSet
  name: kops-controller
  namespace: kube-system
  resourceVersion: "313"
  uid: 012f30a0-d5d2-46d8-a5a1-1bc25c99728a
kind: Event
lastTimestamp: "2020-09-06T09:46:37Z"
message: 'Created pod: kops-controller-n2rch'
metadata:
  creationTimestamp: "2020-09-06T09:46:37Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject:
        f:apiVersion: {}
        f:kind: {}
        f:name: {}
        f:namespace: {}
        f:resourceVersion: {}
        f:uid: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-06T09:46:37Z"
  name: kops-controller.163228ba131cd637
  namespace: kube-system
reason: SuccessfulCreate
reportingComponent: ""
reportingInstance: ""
source:
  component: daemonset-controller
type: Normal
