apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2020-09-06T09:46:55Z"
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{kops-controller}
  kind: Pod
  name: kops-controller-n2rch
  namespace: kube-system
  resourceVersion: "473"
  uid: 394e7992-ca86-4677-8f24-aed3626b1b88
kind: Event
lastTimestamp: "2020-09-06T09:46:55Z"
message: Created container kops-controller
metadata:
  creationTimestamp: "2020-09-06T09:46:55Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject:
        f:apiVersion: {}
        f:fieldPath: {}
        f:kind: {}
        f:name: {}
        f:namespace: {}
        f:resourceVersion: {}
        f:uid: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
        f:host: {}
      f:type: {}
    manager: kubelet
    operation: Update
    time: "2020-09-06T09:46:55Z"
  name: kops-controller-n2rch.163228be597056ae
  namespace: kube-system
reason: Created
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: ip-172-20-47-215.us-west-2.compute.internal
type: Normal
