apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2020-09-06T09:47:30Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: kube-dns-64f86fb8dd-wcbmt
  namespace: kube-system
  resourceVersion: "568"
  uid: 71924c65-3efc-4a0c-b544-514cd1dbe8e8
kind: Event
lastTimestamp: "2020-09-06T09:47:30Z"
message: Successfully assigned kube-system/kube-dns-64f86fb8dd-wcbmt to ip-172-20-46-143.us-west-2.compute.internal
metadata:
  creationTimestamp: "2020-09-06T09:47:30Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject:
        f:apiVersion: {}
        f:kind: {}
        f:name: {}
        f:namespace: {}
        f:resourceVersion: {}
        f:uid: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
      f:type: {}
    manager: kube-scheduler
    operation: Update
    time: "2020-09-06T09:47:30Z"
  name: kube-dns-64f86fb8dd-wcbmt.163228c67c98a0dc
  namespace: kube-system
reason: Scheduled
reportingComponent: ""
reportingInstance: ""
source:
  component: default-scheduler
type: Normal
