apiVersion: coordination.k8s.io/v1beta1
kind: Lease
metadata:
  creationTimestamp: "2020-09-06T09:45:53Z"
  managedFields:
  - apiVersion: coordination.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:acquireTime: {}
        f:holderIdentity: {}
        f:leaseDurationSeconds: {}
        f:leaseTransitions: {}
        f:renewTime: {}
    manager: kube-scheduler
    operation: Update
    time: "2020-09-06T10:36:16Z"
  name: kube-scheduler
  namespace: kube-system
spec:
  acquireTime: "2020-09-06T09:45:53.000000Z"
  holderIdentity: ip-172-20-47-215_aa1e72d9-2c6c-4e71-9cbe-91811101b6d9
  leaseDurationSeconds: 15
  leaseTransitions: 0
  renewTime: "2020-09-06T10:36:16.297313Z"
