apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: 2dacea89b75176b1c0d80ab9ab8277ee
    kubernetes.io/config.mirror: 2dacea89b75176b1c0d80ab9ab8277ee
    kubernetes.io/config.seen: "2020-09-06T09:44:19.850113693Z"
    kubernetes.io/config.source: file
    scheduler.alpha.kubernetes.io/critical-pod: ""
  creationTimestamp: "2020-09-06T09:46:06Z"
  labels:
    k8s-app: etcd-manager-events
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/config.hash: {}
          f:kubernetes.io/config.mirror: {}
          f:kubernetes.io/config.seen: {}
          f:kubernetes.io/config.source: {}
          f:scheduler.alpha.kubernetes.io/critical-pod: {}
        f:labels:
          .: {}
          f:k8s-app: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"a1ab8423-fa81-4599-aad1-d8aad4aeec7d"}:
            .: {}
            f:apiVersion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:containers:
          k:{"name":"etcd-manager"}:
            .: {}
            f:command: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:privileged: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/kubernetes/pki/etcd-manager"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/rootfs"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/log/etcd.log"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:hostNetwork: {}
        f:hostPID: {}
        f:nodeName: {}
        f:priorityClassName: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
        f:tolerations: {}
        f:volumes:
          .: {}
          k:{"name":"pki"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
          k:{"name":"rootfs"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
          k:{"name":"varlogetcd"}:
            .: {}
            f:hostPath:
              .: {}
              f:path: {}
              f:type: {}
            f:name: {}
      f:status:
        f:conditions:
          .: {}
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"PodScheduled"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"172.20.47.215"}:
            .: {}
            f:ip: {}
        f:qosClass: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2020-09-06T09:46:20Z"
  name: etcd-manager-events-ip-172-20-47-215.us-west-2.compute.internal
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Node
    name: ip-172-20-47-215.us-west-2.compute.internal
    uid: a1ab8423-fa81-4599-aad1-d8aad4aeec7d
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - mkfifo /tmp/pipe; (tee -a /var/log/etcd.log < /tmp/pipe & ) ; exec /etcd-manager
      --backup-store=s3://k8s-kops-gossip-state/mycluster.k8s.local/backups/etcd/events
      --client-urls=https://__name__:4002 --cluster-name=etcd-events --containerized=true
      --dns-suffix=internal.mycluster.k8s.local --etcd-insecure=false --grpc-port=3997
      --insecure=false --peer-urls=https://__name__:2381 --quarantine-client-urls=https://__name__:3995
      --v=6 --volume-name-tag=k8s.io/etcd/events --volume-provider=aws --volume-tag=k8s.io/etcd/events
      --volume-tag=k8s.io/role/master=1 --volume-tag=kubernetes.io/cluster/mycluster.k8s.local=owned
      > /tmp/pipe 2>&1
    image: kopeio/etcd-manager:3.0.20200531
    imagePullPolicy: IfNotPresent
    name: etcd-manager
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /rootfs
      name: rootfs
    - mountPath: /etc/kubernetes/pki/etcd-manager
      name: pki
    - mountPath: /var/log/etcd.log
      name: varlogetcd
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  nodeName: ip-172-20-47-215.us-west-2.compute.internal
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /
      type: Directory
    name: rootfs
  - hostPath:
      path: /etc/kubernetes/pki/etcd-manager-events
      type: DirectoryOrCreate
    name: pki
  - hostPath:
      path: /var/log/etcd-events.log
      type: FileOrCreate
    name: varlogetcd
