apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"policy/v1beta1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"name":"kube-dns","namespace":"kube-system"},"spec":{"minAvailable":1,"selector":{"matchLabels":{"k8s-app":"kube-dns"}}}}
  creationTimestamp: "2020-09-06T09:45:34Z"
  managedFields:
  - apiVersion: policy/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:minAvailable: {}
        f:selector:
          .: {}
          f:matchLabels:
            .: {}
            f:k8s-app: {}
    manager: kubectl
    operation: Update
    time: "2020-09-06T09:45:34Z"
  - apiVersion: policy/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:currentHealthy: {}
        f:desiredHealthy: {}
        f:disruptionsAllowed: {}
        f:expectedPods: {}
        f:observedGeneration: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-06T09:48:03Z"
  name: kube-dns
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
