apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJ1Z0F3SUJBZ0lNRmpJb1hMSXZrdmN0TFdycU1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1qQXdPVEEwTURrek9UVTJXaGNOTXpBd09UQTBNRGt6T1RVMgpXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQWxtUkRkTk5YZlI3ZzhXTXc2d1puQVRPWDBJOHhza28wNWRSK01DYzloOUt4UVkraitBaXUKSUZ3Vk1TeTgvV3BIMS9paDJHdzk2NmZuWmR3NHkrUWlIZDA0WnJ1SmsxS0tDQVAySGVvVTZNVW5iWGUzTk9RYgpTam05WEJDczBBNCtpR3R3YkRQa3gyK0lrVS96YWJxcXAvRzY3OHpqOGRDS0tlQ2NhWnhqOFlzWnJzUE5wRTBqCkhxSDlIcHdwd2xGMkNlTXprMDlzY1J1S3ZjWGZXMlNqQ0Y0TTlJaXBJZStBTHE0SnEzT3YrenVBWEl3OWs2Q2YKUFdBdGV4TDIvUlZaeVVBL2RUWHlTaXRDMmpRYkxBVmlqeWt2OXAzOVQzQ2ExdDRPRUlUb0VDVjU5bG43NW9zdwo0cmZoc2hUcjI3VWZpL0cvZlFyY0NyOXhnNHRneXhwVWF3SURBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFqcTZISlQ3ZWRnZm4KQVRRdDVaZWdua0ppZlVENUkxdTh5TUhrK0VFVWVoKzJiSkFBa3dLS2hFVW4rMTllRmdST3JkRDJzaHVzK0cwVQpROTl6OWM0RHhyTkJwMG5rcmNCeklFZUhpOXFvQmVlei9WNDI4ZWxtYURSUTYrT0did2J3REVKT3A0cy9hVVhkCkJjeXpBcGROUGt5SG1EdjhtMEJlNjVUMHhVQzY2NzZrVHVGckw5ZWt2ZDB2UzVXd0tjc1RwOXNZMi9QeVY0cGQKcVBWS29jQmdlM2NKWHNucWZXV0U0VmRNdUhxbFAvU2pqc1J3TDc5c05PVnRWOGtNV2FEQjczVUdEdlJhNXFiSgpLL1NQWVJtUG1MQzRzOW5xTU01Mk91TUdCa0VBK1dSM2JNOUk1WWFGQkVwUEpSakh4U1JaZnFQMFlkemMvM3RZCjNidHdDb3RhMWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: a3ViZS1zeXN0ZW0=
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrNHpiMVkzV0dabk1YSm1ObGR2YjI5SlRqTnRZazV2TFhaalNYcHdZMlo0Y0daT2EybDFRVWRmZGtVaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKd2IyUXRaMkZ5WW1GblpTMWpiMnhzWldOMGIzSXRkRzlyWlc0dGNHdDNOMk1pTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1dVlXMWxJam9pY0c5a0xXZGhjbUpoWjJVdFkyOXNiR1ZqZEc5eUlpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVkV2xrSWpvaVpEbGtNalZtWVRrdFkySTVPQzAwWVRreExXRmpOV0V0TWpKbU16aGpOMlEyT1dZMElpd2ljM1ZpSWpvaWMzbHpkR1Z0T25ObGNuWnBZMlZoWTJOdmRXNTBPbXQxWW1VdGMzbHpkR1Z0T25CdlpDMW5ZWEppWVdkbExXTnZiR3hsWTNSdmNpSjkuRVRTcFNvclE1MV93TmktT25acmZkREtDTXg0VC14QU5XcW5fUmE2TlZrM2YzUmNfRzhrVzliemlUdmZ6THAweWNlNmZiRmZKSTQyYlVkZzFtbmdQV1dEYUFtTm8zUEtrMVBudnFHSzhYWU0wY2RLbFZ5T2lvSktMRk1iVEhFbkRrQ2syVGdWTk84Q21kNE9MZFl4WEtnd1Z3N0tWOUlGTnpYV3RmQU1ETXlMOE1wTm9oS21HaW9mRWdZOXdBVWg3U1RaM2U4VnFZVlkwV25RQlhkZUhCaGd4dzBacHNLMzMyOHlYWm5YNUpWdTc4WVZodTRrdXRtYWF0eHRSRnlHeEU4SlJHZGgwMGwwZ05qV1RGRGJwNTJCWTRMWHNYampuZHNSNGFlQ3l5Njl0SVFlSGduYlZMZWlRUktVVGlYTTV3ZC15bDE3eFpCVGhjcC1MRllvcEtR
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: pod-garbage-collector
    kubernetes.io/service-account.uid: d9d25fa9-cb98-4a91-ac5a-22f38c7d69f4
  creationTimestamp: "2020-09-06T09:45:51Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-06T09:45:51Z"
  name: pod-garbage-collector-token-pkw7c
  namespace: kube-system
type: kubernetes.io/service-account-token
