apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJ1Z0F3SUJBZ0lNRmpJb1hMSXZrdmN0TFdycU1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1qQXdPVEEwTURrek9UVTJXaGNOTXpBd09UQTBNRGt6T1RVMgpXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQWxtUkRkTk5YZlI3ZzhXTXc2d1puQVRPWDBJOHhza28wNWRSK01DYzloOUt4UVkraitBaXUKSUZ3Vk1TeTgvV3BIMS9paDJHdzk2NmZuWmR3NHkrUWlIZDA0WnJ1SmsxS0tDQVAySGVvVTZNVW5iWGUzTk9RYgpTam05WEJDczBBNCtpR3R3YkRQa3gyK0lrVS96YWJxcXAvRzY3OHpqOGRDS0tlQ2NhWnhqOFlzWnJzUE5wRTBqCkhxSDlIcHdwd2xGMkNlTXprMDlzY1J1S3ZjWGZXMlNqQ0Y0TTlJaXBJZStBTHE0SnEzT3YrenVBWEl3OWs2Q2YKUFdBdGV4TDIvUlZaeVVBL2RUWHlTaXRDMmpRYkxBVmlqeWt2OXAzOVQzQ2ExdDRPRUlUb0VDVjU5bG43NW9zdwo0cmZoc2hUcjI3VWZpL0cvZlFyY0NyOXhnNHRneXhwVWF3SURBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFqcTZISlQ3ZWRnZm4KQVRRdDVaZWdua0ppZlVENUkxdTh5TUhrK0VFVWVoKzJiSkFBa3dLS2hFVW4rMTllRmdST3JkRDJzaHVzK0cwVQpROTl6OWM0RHhyTkJwMG5rcmNCeklFZUhpOXFvQmVlei9WNDI4ZWxtYURSUTYrT0did2J3REVKT3A0cy9hVVhkCkJjeXpBcGROUGt5SG1EdjhtMEJlNjVUMHhVQzY2NzZrVHVGckw5ZWt2ZDB2UzVXd0tjc1RwOXNZMi9QeVY0cGQKcVBWS29jQmdlM2NKWHNucWZXV0U0VmRNdUhxbFAvU2pqc1J3TDc5c05PVnRWOGtNV2FEQjczVUdEdlJhNXFiSgpLL1NQWVJtUG1MQzRzOW5xTU01Mk91TUdCa0VBK1dSM2JNOUk1WWFGQkVwUEpSakh4U1JaZnFQMFlkemMvM3RZCjNidHdDb3RhMWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: a3ViZS1zeXN0ZW0=
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrNHpiMVkzV0dabk1YSm1ObGR2YjI5SlRqTnRZazV2TFhaalNYcHdZMlo0Y0daT2EybDFRVWRmZGtVaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKd2RtTXRjSEp2ZEdWamRHbHZiaTFqYjI1MGNtOXNiR1Z5TFhSdmEyVnVMVFI2TlRZMElpd2lhM1ZpWlhKdVpYUmxjeTVwYnk5elpYSjJhV05sWVdOamIzVnVkQzl6WlhKMmFXTmxMV0ZqWTI5MWJuUXVibUZ0WlNJNkluQjJZeTF3Y205MFpXTjBhVzl1TFdOdmJuUnliMnhzWlhJaUxDSnJkV0psY201bGRHVnpMbWx2TDNObGNuWnBZMlZoWTJOdmRXNTBMM05sY25acFkyVXRZV05qYjNWdWRDNTFhV1FpT2lJeU9EQXlZalkxTVMwek16QmtMVFJrWTJZdFlqaGxOeTAyTnpWaE16SmhOams1TW1NaUxDSnpkV0lpT2lKemVYTjBaVzA2YzJWeWRtbGpaV0ZqWTI5MWJuUTZhM1ZpWlMxemVYTjBaVzA2Y0haakxYQnliM1JsWTNScGIyNHRZMjl1ZEhKdmJHeGxjaUo5LkRsTDZOLUQxVXhxdU1rZEozUUxFRmpHNFRaMHZxaDZTYnB1bkVRRHdPR0VQdGlveUxrbWdZVE51NFlINkp5bUhvUjRlWUZvZ25ET1N6RUdMYmFhd2hzLXZQVDc2N005RFBXMllFVnJYMnlFTmxGVFlnV0NyM3dBU2JiamdoZTlGUG1TSmxZUnV5NER5dHQtMFFEYjVqT25OSWgwcTgzeUdnLWU4MXpXSUktXy0wUG4xX2J4OVNFZ0R2bVVsTjVqQlNBR1M1WTd1ekMxRkxYTlNSQzdjYmxXRzJGTmJUeEtTdzliTFlBLW8zNDRHREc5dlpYZU1Mb0pqSzFOYzRsbVlvOTVNYkNlYUI3WGo0Rkd3Y1VmdXZSbnVmdER2ZWdhMEo5Q0FvbGZBT2N5Y2U3TzBRRkZVUm9fYTNKWDdzR3pINjdZakdoZlhBWVU0X1RWNVFyMW1hZw==
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: pvc-protection-controller
    kubernetes.io/service-account.uid: 2802b651-330d-4dcf-b8e7-675a32a6992c
  creationTimestamp: "2020-09-06T09:45:49Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-06T09:45:49Z"
  name: pvc-protection-controller-token-4z564
  namespace: kube-system
type: kubernetes.io/service-account-token
