apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJ1Z0F3SUJBZ0lNRmpJb1hMSXZrdmN0TFdycU1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1qQXdPVEEwTURrek9UVTJXaGNOTXpBd09UQTBNRGt6T1RVMgpXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQWxtUkRkTk5YZlI3ZzhXTXc2d1puQVRPWDBJOHhza28wNWRSK01DYzloOUt4UVkraitBaXUKSUZ3Vk1TeTgvV3BIMS9paDJHdzk2NmZuWmR3NHkrUWlIZDA0WnJ1SmsxS0tDQVAySGVvVTZNVW5iWGUzTk9RYgpTam05WEJDczBBNCtpR3R3YkRQa3gyK0lrVS96YWJxcXAvRzY3OHpqOGRDS0tlQ2NhWnhqOFlzWnJzUE5wRTBqCkhxSDlIcHdwd2xGMkNlTXprMDlzY1J1S3ZjWGZXMlNqQ0Y0TTlJaXBJZStBTHE0SnEzT3YrenVBWEl3OWs2Q2YKUFdBdGV4TDIvUlZaeVVBL2RUWHlTaXRDMmpRYkxBVmlqeWt2OXAzOVQzQ2ExdDRPRUlUb0VDVjU5bG43NW9zdwo0cmZoc2hUcjI3VWZpL0cvZlFyY0NyOXhnNHRneXhwVWF3SURBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFqcTZISlQ3ZWRnZm4KQVRRdDVaZWdua0ppZlVENUkxdTh5TUhrK0VFVWVoKzJiSkFBa3dLS2hFVW4rMTllRmdST3JkRDJzaHVzK0cwVQpROTl6OWM0RHhyTkJwMG5rcmNCeklFZUhpOXFvQmVlei9WNDI4ZWxtYURSUTYrT0did2J3REVKT3A0cy9hVVhkCkJjeXpBcGROUGt5SG1EdjhtMEJlNjVUMHhVQzY2NzZrVHVGckw5ZWt2ZDB2UzVXd0tjc1RwOXNZMi9QeVY0cGQKcVBWS29jQmdlM2NKWHNucWZXV0U0VmRNdUhxbFAvU2pqc1J3TDc5c05PVnRWOGtNV2FEQjczVUdEdlJhNXFiSgpLL1NQWVJtUG1MQzRzOW5xTU01Mk91TUdCa0VBK1dSM2JNOUk1WWFGQkVwUEpSakh4U1JaZnFQMFlkemMvM3RZCjNidHdDb3RhMWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: a3ViZS1zeXN0ZW0=
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrNHpiMVkzV0dabk1YSm1ObGR2YjI5SlRqTnRZazV2TFhaalNYcHdZMlo0Y0daT2EybDFRVWRmZGtVaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpyZFdKbExYTjVjM1JsYlNJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZqY21WMExtNWhiV1VpT2lKalpYSjBhV1pwWTJGMFpTMWpiMjUwY205c2JHVnlMWFJ2YTJWdUxUbGpkM0pqSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWJtRnRaU0k2SW1ObGNuUnBabWxqWVhSbExXTnZiblJ5YjJ4c1pYSWlMQ0pyZFdKbGNtNWxkR1Z6TG1sdkwzTmxjblpwWTJWaFkyTnZkVzUwTDNObGNuWnBZMlV0WVdOamIzVnVkQzUxYVdRaU9pSmhZakUyT0dKaU1TMHdaak0wTFRSbE5ERXRPV1U0TXkwMk5EWmtOVEkzWmpCa1pURWlMQ0p6ZFdJaU9pSnplWE4wWlcwNmMyVnlkbWxqWldGalkyOTFiblE2YTNWaVpTMXplWE4wWlcwNlkyVnlkR2xtYVdOaGRHVXRZMjl1ZEhKdmJHeGxjaUo5Lk1wU1JOT3NkbDR5Q1RVZVhPbkRIeHlndTNnWmNCNmRJbDNXV3pHOVZmcHNZMk9LQ2N5Vk4tNnVJQlB4dk1nU05Lc1VpazFmYVBBWGpFTnZjTnRCWG13czdpUDdadG1yang2bDA5ZWxiaXJ1Snd0VnVyd0htUFYzWVpWUmtzOTF0WmJydll1QzZvdGFpQVhra2JVaF9JdlA4dnVXTUNHV1pmOTRFLTBQeFlwb2J3UkgtSEVwVFI3TzFDX1BMdlJva1NqT2hoUkhQa0EtWGtMUjlZOVlrQVJnLWtGV0dmaXRnSF9McTl3a1Z5cTd3b3NuRnFvanZmT3BOcDlTRHl3NWdWeE51aW1xS3NwZU9maXdOWEMtbVo0QmhoVW91Q2FCbjJrejd6OUZQOS1UWUlzZW0zNlBJb3BUY1p4ZUhIRFI3d0ROOWhSdUl5Mld4cVpQYldFTGxWdw==
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: certificate-controller
    kubernetes.io/service-account.uid: ab168bb1-0f34-4e41-9e83-646d527f0de1
  creationTimestamp: "2020-09-06T09:45:49Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-06T09:45:49Z"
  name: certificate-controller-token-9cwrc
  namespace: kube-system
type: kubernetes.io/service-account-token
