apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"k8s-addon":"kube-dns.addons.k8s.io"},"name":"kube-dns-autoscaler","namespace":"kube-system"}}
  creationTimestamp: "2020-09-06T09:45:34Z"
  labels:
    k8s-addon: kube-dns.addons.k8s.io
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:k8s-addon: {}
    manager: kubectl
    operation: Update
    time: "2020-09-06T09:45:34Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:secrets:
        .: {}
        k:{"name":"kube-dns-autoscaler-token-z8hbp"}:
          .: {}
          f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-06T09:45:36Z"
  name: kube-dns-autoscaler
  namespace: kube-system
secrets:
- name: kube-dns-autoscaler-token-z8hbp
