apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-09-06T09:45:46Z"
  name: attachdetach-controller
  namespace: kube-system
secrets:
- name: attachdetach-controller-token-8qzk2
