apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"k8s-addon":"kops-controller.addons.k8s.io"},"name":"kops-controller","namespace":"kube-system"}}
  creationTimestamp: "2020-09-06T09:45:36Z"
  labels:
    k8s-addon: kops-controller.addons.k8s.io
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:secrets:
        .: {}
        k:{"name":"kops-controller-token-8r9l8"}:
          .: {}
          f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-09-06T09:45:36Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:k8s-addon: {}
    manager: kubectl
    operation: Update
    time: "2020-09-06T09:45:36Z"
  name: kops-controller
  namespace: kube-system
secrets:
- name: kops-controller-token-8r9l8
